### ISSUE TITLE
LIBUSB_ERROR_ACCESS [-3]

### ISSUE THREAD

**Issue by baruchl** [google/python-adb#103]
Dear @fahhem ,
While running the example code (in readme file) as is, I'm getting every once and then (no specific number of runs) the LIBUSB_ERROR_ACCESS [-3].
I'm aware that using kill adb-server will solve the issue, but it renders the ADB library useless, since I will need to call the kill adb from a different process using regular adb.
Why the ADB library doesn't make sure it leaves the state clean so all consecutive calls will work?

Additional details:
1. Windows 10 RS2 OS
2. i used the latest version from main

Here is the full error:

`C:\Python27\python.exe C:/Users/baruchl/Documents/_GIT/python-adb/adb/MyTest.py
Traceback (most recent call last):
  File "C:/Users/baruchl/Documents/_GIT/python-adb/adb/MyTest.py", line 30, in <module>
    try_adb_python()
  File "C:/Users/baruchl/Documents/_GIT/python-adb/adb/MyTest.py", line 17, in try_adb_python
    print devices[0].serial_number
  File "C:\Users\baruchl\Documents\_GIT\python-adb\adb\common.py", line 139, in serial_number
    return self._device.getSerialNumber()
  File "C:\Python27\lib\site-packages\usb1\__init__.py", line 2040, in getSerialNumber
1
    self.device_descriptor.iSerialNumber)
  File "C:\Python27\lib\site-packages\usb1\__init__.py", line 2017, in _getASCIIStringDescriptor
    return self.open().getASCIIStringDescriptor(descriptor)
  File "C:\Python27\lib\site-packages\usb1\__init__.py", line 2067, in open
    mayRaiseUSBError(libusb1.libusb_open(self.device_p, byref(handle)))
  File "C:\Python27\lib\site-packages\usb1\__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "C:\Python27\lib\site-packages\usb1\__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]`

**Comment by fahhem** [comment]
Normally, the adb server is started by an adb command, or by some process like an emulator. If you switch to python-adb entirely (and don't use emulators), then the adb server shouldn't be running anymore.

We can't be in charge of stopping adb servers, because if it's running, it's likely being used by another process, and we don't want to cause errors in other programs that become impossible to diagnose.

If you manage to stop the adb server and stop it from coming back, python-adb can be useful to you, but until then only one process can 'own' a USB device and if the adb server is running it's 'owning' all android USB devices.

**Comment by CoXier** [comment]
So how to stop it from coming back?
