### ISSUE TITLE
Pull error connection

### ISSUE THREAD

**Issue by vBlackOut** [google/python-adb#125]
```Traceback (most recent call last):
  File "/home/fc_dev/python/Actions/attackTitan.py", line 29, in main
    self.Console.pullShell("/sdcard/screen.png", "screen.png")
  File "/home/fc_dev/python/Tools/shell.py", line 29, in pullShell
    self.device.Pull(remote)
  File "/home/fc_dev/python/adb/adb_commands.py", line 303, in Pull
    self.filesync_handler.Pull(conn, device_filename, dest_file, progress_callback)
  File "/home/fc_dev/python/adb/filesync_protocol.py", line 94, in Pull
    for cmd_id, _, data in cnxn.ReadUntil((b'DATA',), b'DONE'):
  File "/home/fc_dev/python/adb/filesync_protocol.py", line 243, in ReadUntil
    cmd_id, header, data = self.Read(expected_ids + finish_ids)
  File "/home/fc_dev/python/adb/filesync_protocol.py", line 215, in Read
    self._Flush()
  File "/home/fc_dev/python/adb/filesync_protocol.py", line 255, in _Flush
    self.adb.Write(self.send_buffer[:self.send_idx])
AttributeError: 'NoneType' object has no attribute 'Write'
```

my use pull script

```
adb.Pull("/sdcard/screen.png", "screen.png")
```

Weird i look the self.adb is not implemented method 

i try to look for print(dir(self.adb))

the return 

```
['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
```

thank for looking

**Comment by penn5** [comment]
I have the same issue - 
```
b'device'
Traceback (most recent call last):
  File "autoroot.py", line 123, in <module>
    install_firmware(dloadfirmware, device)
  File "autoroot.py", line 120, in install_firmware
    print(device.Push(os.path.join(d, 'Software', 'dload'), storage+'/dload', timeout_ms=100000))
  File "/home/penn/python-adb/adb/adb_commands.py", line 269, in Push
    progress_callback=progress_callback)
  File "/home/penn/python-adb/adb/adb_commands.py", line 280, in Push
    mtime=int(mtime), progress_callback=progress_callback, **kwargs)
  File "/home/penn/python-adb/adb/filesync_protocol.py", line 149, in Push
    cnxn.Send(b'DATA', data)
  File "/home/penn/python-adb/adb/filesync_protocol.py", line 207, in Send
    self._Flush()
  File "/home/penn/python-adb/adb/filesync_protocol.py", line 254, in _Flush
    self.adb.Write(self.send_buffer[:self.send_idx])
AttributeError: 'NoneType' object has no attribute 'Write'
```

**Comment by vBlackOut** [comment]
For me solve temporary Look here for me solve my problem temporary https://github.com/google/python-adb/issues/132
