### ISSUE TITLE
Can't run abootool-TypeError: __init__() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by bene2929** [google/python-adb#149]
Upon running the script, it finds the device and immdiately throws an error and stops. The following output is produced:
`python abootool.py 
INFO: Welcome to abootool by Aleph Research, HCL technologies
INFO: fastboot connected to 710KPRW0428622
Traceback (most recent call last):
  File "abootool.py", line 95, in <module>
    sys.exit(main())
  File "abootool.py", line 73, in main
    name = dev.device()
  File "/home/dakantz/abootool/device.py", line 272, in device
    return Config.bootloader_names[self.bootloader_name()]
  File "/home/dakantz/abootool/device.py", line 260, in bootloader_name
    p = self.product()
  File "/home/dakantz/abootool/device.py", line 248, in product
    return self.getvar("product")
  File "/home/dakantz/abootool/device.py", line 241, in getvar
    self.data[k] = self.wait_for_fb_command("Getvar", False, False, k)
  File "/home/dakantz/abootool/device.py", line 189, in wait_for_fb_command
    self.resolve_fb_error()
  File "/home/dakantz/abootool/device.py", line 304, in resolve_fb_error
    self.fb_error = self.do_fb_command("Oem", True, Config.oem_error_cmd)
  File "/home/dakantz/abootool/device.py", line 158, in do_fb_command
    getattr(self.fastboot(), func)(info_cb=self.last_output, *args, **kargs)
  File "/home/dakantz/abootool/device.py", line 140, in fastboot
    return fastboot.FastbootCommands(self.usbdev)
TypeError: __init__() takes exactly 1 argument (2 given)
`

**Comment by bene2929** [comment]
Wrong repo
