### ISSUE TITLE
Problems installing through pip (ubunutu)

### ISSUE THREAD

**Issue by wouterverduin** [google/python-adb#154]
Hi all! 

Was looking for software like this to controle my Nvidia Shield. After some reading found this should do the trick.

However; after attempting to install using 'pip install adb' it throws an error:

    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-iFFlkd/M2Crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Ahd8mj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-iFFlkd/M2Crypto/

Anyway to resolve this?

**Comment by gilazov** [comment]
Try to use `pip install rsa`, then `pip install adb`. It works for me.

**Comment by gilazov** [comment]
It works for me:
$ apt-get install libssl-dev libffi-dev
$ sudo pip install openssl
$ pip install --global-option=build_ext --global-option="-I/usr/local/opt/openssl/include" m2crypto

**Comment by topherbuckley** [comment]
I also get the same errors as @wouterverduin. I also don't see any package named openssl as mentioned by @gilazov for python3 other than openssl-python (0.1). I tried to install that, but it failed with the following message:

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-uip3wbp7/openssl-python/setup.py", line 7, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/usr/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-uip3wbp7/openssl-python/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-uip3wbp7/openssl-python/

@gilazov were you installing using python2? Some of these dependencies may not work with python3 perhaps?

**Comment by penn5** [comment]
If you install python-rsa and build from master rather than the latest pypi release (#133) it works. M2Crypto doesn't work on Python3/Linux for me, always an error.

**Comment by bannsec** [comment]
penn5's solution worked for me. I guess you just gotta know the secret handshake to be able to install correctly.

**Comment by BitbeyHub** [comment]
I have the same problem.
