### ISSUE TITLE
I cannot run python2.7 adb.zip shell on my Ubuntu 14.04

### ISSUE THREAD

**Issue by caiyesd** [google/python-adb#26]
$ python2.7 adb.zip shell ls
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "adb.zip/__main__.py", line 178, in <module>
  File "adb.zip/__main__.py", line 174, in main
  File "adb.zip/adb/common_cli.py", line 150, in StartCli
  File "adb.zip/adb/adb_commands.py", line 75, in ConnectDevice
  File "adb.zip/adb/common.py", line 208, in FindAndOpen
  File "adb.zip/adb/common.py", line 122, in Open
  File "build/bdist.linux-x86_64/egg/usb1.py", line 1162, in claimInterface
  File "build/bdist.linux-x86_64/egg/usb1.py", line 121, in mayRaiseUSBError
  File "build/bdist.linux-x86_64/egg/usb1.py", line 117, in raiseUSBError
usb1.USBErrorBusy: LIBUSB_ERROR_BUSY [-6

**Comment by fahhem** [comment]
This error typically happens when your user doesn't have access to the
device. Does adb from Android work?

**Comment by caiyesd** [comment]
@fahhem Yes. The adb from Android SDK works.


jiangxin@JX-PC:~/Local/github/python-adb$ **python2.7 adb.zip shell ls**
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "adb.zip/__main__.py", line 178, in <module>
  File "adb.zip/__main__.py", line 174, in main
  File "adb.zip/adb/common_cli.py", line 150, in StartCli
  File "adb.zip/adb/adb_commands.py", line 75, in ConnectDevice
  File "adb.zip/adb/common.py", line 208, in FindAndOpen
  File "adb.zip/adb/common.py", line 122, in Open
  File "build/bdist.linux-x86_64/egg/usb1.py", line 1162, in claimInterface
  File "build/bdist.linux-x86_64/egg/usb1.py", line 121, in mayRaiseUSBError
  File "build/bdist.linux-x86_64/egg/usb1.py", line 117, in raiseUSBError
usb1.USBErrorBusy: LIBUSB_ERROR_BUSY [-6]
jiangxin@JX-PC:~/Local/github/python-adb$ **adb shell ls**
acct
cache
charger
config
d
data
default.prop
dev
etc
file_contexts
firmware
fstab.hammerhead
init
init.environ.rc
init.hammerhead.diag.rc
init.hammerhead.rc
init.hammerhead.usb.rc
init.rc
init.trace.rc
init.usb.configfs.rc
init.usb.rc
init.zygote32.rc
mnt
oem
persist
proc
property_contexts
res
root
sbin
sdcard
seapp_contexts
selinux_version
sepolicy
service_contexts
storage
sys
system
ueventd.hammerhead.rc
ueventd.rc
vendor

**Comment by fahhem** [comment]
Ah, I see, you have the Android adb running in the background :)

Run `adb kill-server` then you should be able to use adb.zip!

**Comment by caiyesd** [comment]
Great! thanks a lot.

**Comment by mostafa1611** [comment]
Hi Fahhem.
I am runing this command in ubuntu 16.x 64 bits :


python2 adb.zip shell ls /sdcard
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "adb.zip/__main__.py", line 178, in <module>
  File "adb.zip/__main__.py", line 174, in main
  File "adb.zip/adb/common_cli.py", line 150, in StartCli
  File "adb.zip/adb/adb_commands.py", line 76, in ConnectDevice
  File "adb.zip/adb/adb_commands.py", line 99, in Connect
  File "adb.zip/adb/adb_protocol.py", line 283, in Connect
  File "adb.zip/adb/adb_protocol.py", line 241, in Read
  File "adb.zip/adb/adb_protocol.py", line 189, in CalculateChecksum
TypeError: ord() expected string of length 1, but int found
I am using python 2.7.12, any help?
Thank you in advance.

**Comment by fahhem** [comment]
Sorry about the delay on this project, I haven't had a system with an ADB device I could use this all with in a while. I've just pushed a commit to fix this problem in particular.
