### ISSUE TITLE
python adb.zip shell fails on macOS Sierra 10.12.1

### ISSUE THREAD

**Issue by bootstraponline** [google/python-adb#30]
I'm using Python 2.7.12 on macOS Sierra 10.12.1. 

```
$  python adb.zip shell
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "adb.zip/__main__.py", line 178, in <module>
  File "adb.zip/__main__.py", line 174, in main
  File "adb.zip/adb/common_cli.py", line 150, in StartCli
  File "adb.zip/adb/adb_commands.py", line 75, in ConnectDevice
  File "adb.zip/adb/common.py", line 208, in FindAndOpen
  File "adb.zip/adb/common.py", line 122, in Open
  File "/usr/local/lib/python2.7/site-packages/usb1.py", line 1183, in claimInterface
    libusb1.libusb_claim_interface(self.__handle, interface),
  File "/usr/local/lib/python2.7/site-packages/usb1.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/usr/local/lib/python2.7/site-packages/usb1.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]
```

**Comment by fahhem** [comment]
Make sure Android adb isn't running:

```
adb kill-server
```

Does that fix it?

**Comment by bootstraponline** [comment]
Yes. Thanks.
