### ISSUE TITLE
TcpHandle: TCP connection port parse error

### ISSUE THREAD

**Issue by thica** [google/python-adb#32]
In common.py, you split (in init of TcpHandle) the given serial (which in effect is host:port). port results as a string, but socket expects port to be numeric in socket.create_connection

Python 2.7

**Comment by fahhem** [comment]
Hmm, `TcpHandle` was a contributed class which I know the contributor uses, so it's odd that it would have such a blatant bug. If you're able to test your changes, then a pull request would be accepted.

**Comment by thica** [comment]
Hi,

its tested

`class TcpHandle(object):
  """TCP connection object.

     Provides same interface as UsbHandle but ignores timeout."""

  def __init__(self, serial):
    """Initialize the TCP Handle.
    Arguments:
      serial: Android device serial of the form host or host:port.

    Host may be an IP address or a host name.
    """
    if ':' in serial:
      (host, port) = serial.split(':')
      port_int=int(port)  # CTH Code adjusted
    else:
      host = serial
      port = 5555
    self._serial_number = '%s:%s' % (host, port)

    self._connection = socket.create_connection((host, port_int))  # CTH Code adjusted
    `

You can easy tell, that the line
port = 5555
indicates a numeric value.

**Comment by thica** [comment]
Sorry just seen, that the default path have to covered as well

`
class TcpHandle(object):
  """TCP connection object.

     Provides same interface as UsbHandle but ignores timeout."""

  def __init__(self, serial):
    """Initialize the TCP Handle.
    Arguments:
      serial: Android device serial of the form host or host:port.

    Host may be an IP address or a host name.
    """
    if ':' in serial:
      (host, port) = serial.split(':')
      port_int=int(port)  # CTH Code adjusted
    else:
      host = serial
      port = '5555' # CTH Code adjusted
      port_int = 5555 # CTH Code adjusted
    self._serial_number = '%s:%s' % (host, port)

    self._connection = socket.create_connection((host, port_int)) # CTH Code adjusted

`

**Comment by AwesomeTurtle** [comment]
Hi @thica ! 

In fact `socket.create_connection` can take a tuple of (String, String) or (String, int).

```python
>>> socket.create_connection(('127.0.0.1', '12800'))
<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 39774), raddr=('127.0.0.1', 12800)>
>>> socket.create_connection(('127.0.0.1', 12800))
<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 39778), raddr=('127.0.0.1', 12800)>

``` 

So we do not need to cast `port` value. 😃

**Comment by thica** [comment]
Hi checked it out, you are right. I am running on an error, as all my strings in my app are unicode, which can't be handled by socket.
 socket.create_connection(('127.0.0.1', u'8080'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\dev\Kivy27\Python27\lib\socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.error: getaddrinfo() argument 2 must be integer or string

**Comment by fahhem** [comment]
You'll need to encode the port as bytes before passing it to TcpHandle then: `port.encode('ascii')`
