### ISSUE TITLE
TypeError: ord() expected string of length 1

### ISSUE THREAD

**Issue by elichai** [google/python-adb#36]
Hi,
I try to use it both with adb.zip and from python and I get this error:

```
Traceback (most recent call last):
  File "/home/elichai2/PycharmProjects/Test/python_adb.py", line 10, in <module>
    rsa_keys=[signer])
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_commands.py", line 76, in ConnectDevice
    return cls.Connect(handle, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_commands.py", line 99, in Connect
    device_state = cls.protocol_handler.Connect(usb, banner=banner, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 277, in Connect
    cmd, arg0, arg1, banner = cls.Read(usb, ['CNXN', 'AUTH'])
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 235, in Read
    actual_checksum = cls.CalculateChecksum(data)
  File "/usr/local/lib/python2.7/dist-packages/adb/adb_protocol.py", line 187, in CalculateChecksum
    return sum(map(ord, data)) & 0xFFFFFFFF
TypeError: ord() expected string of length 1, but int found
```

**Comment by elichai** [comment]
this problem is not only with my code, it happens even if I run `python adb_debug.py shell` or `python adb.zip shell`

**Comment by AwesomeTurtle** [comment]
Hello ! 
I have met this issue while migrating from 2.7 to 3.6. 
I have made a workaround like so : 

 ```python
 @staticmethod
  def CalculateChecksum(data):
    # The checksum is just a sum of all the bytes. I swear.
    if isinstance(data, bytes):
        data = data.decode('ascii')
    return sum(map(ord, data)) & 0xFFFFFFFF
```

**Comment by jbeich** [comment]
It's caused by vpelletier/python-libusb1@b26f6cdbdb26, so try dowgrading to 1.5.3 as more places expect strings.

```python
$ PYTHONPATH=. python2 adb/adb_debug.py shell ls
Traceback (most recent call last):
  File "adb/adb_debug.py", line 178, in <module>
    sys.exit(main())
  File "adb/adb_debug.py", line 174, in main
    rsa_keys=[rsa_signer(path) for path in args.rsa_key_path])
  File "adb/common_cli.py", line 150, in StartCli
    default_timeout_ms=args.timeout_ms, **device_kwargs)
  File "adb/adb_commands.py", line 76, in ConnectDevice
    return cls.Connect(handle, **kwargs)
  File "adb/adb_commands.py", line 99, in Connect
    device_state = cls.protocol_handler.Connect(usb, banner=banner, **kwargs)
  File "adb/adb_protocol.py", line 288, in Connect
    signed_token = rsa_key.Sign(banner)
  File "adb/sign_m2crypto.py", line 30, in Sign
    return self.rsa_key.sign(data, 'sha1')
  File "/usr/local/lib/python2.7/site-packages/M2Crypto/RSA.py", line 246, in sign
    return m2.rsa_sign(self.rsa, digest, digest_type)
TypeError: expected string or Unicode object, bytearray found
```

**Comment by axel-h** [comment]
Shouldn't you use this code in `CalculateChecksum()`:

    if isinstance(data, bytearray):
        return sum(data) & 0xFFFFFFFF

    if isinstance(data, bytes):
        return sum(map(ord, data.decode('ascii'))) & 0xFFFFFFFF

    return sum(map(ord, data)) & 0xFFFFFFFF

at least that seem to work for me now.

**Comment by hotelzululima** [comment]
hi @axel-h ,
        can you code up a pull request  encompassing these fixes and submit it please...

      thanx in advance
      hzl

**Comment by kronenpj** [comment]
Unfortunately, axel-h's changes aren't sufficient. I'm getting this once those changes are in place:
```
Traceback (most recent call last):
  File "adb_sandbox.py", line 12, in <module>
    rsa_keys=[signer])
  File "/usr/lib/python2.7/site-packages/adb/adb_commands.py", line 76, in ConnectDevice
    return cls.Connect(handle, **kwargs)
  File "/usr/lib/python2.7/site-packages/adb/adb_commands.py", line 99, in Connect
    device_state = cls.protocol_handler.Connect(usb, banner=banner, **kwargs)
  File "/usr/lib/python2.7/site-packages/adb/adb_protocol.py", line 296, in Connect
    signed_token = rsa_key.Sign(banner)
  File "/usr/lib/python2.7/site-packages/adb/sign_m2crypto.py", line 30, in Sign
    return self.rsa_key.sign(data, 'sha1')
  File "/usr/lib64/python2.7/site-packages/M2Crypto/RSA.py", line 246, in sign
    return m2.rsa_sign(self.rsa, digest, digest_type)
TypeError: expected string or Unicode object, bytearray found
```

My guess is that there are others..  'adb_sandbox.py' above is the example code from README.md.

**Comment by kronenpj** [comment]
@jbelch Unfortunately downgrading libusb1 to 1.5.3 doesn't really work either. Shell(echo) works, but List('/') emits:
```
Traceback (most recent call last):
  File "adb_sandbox.py", line 16, in <module>
    print(device.List('/'))
  File "build/bdist.linux-x86_64/egg/adb/adb_commands.py", line 204, in List
  File "build/bdist.linux-x86_64/egg/adb/filesync_protocol.py", line 71, in List
  File "build/bdist.linux-x86_64/egg/adb/filesync_protocol.py", line 193, in ReadUntil
  File "build/bdist.linux-x86_64/egg/adb/filesync_protocol.py", line 171, in Read
  File "build/bdist.linux-x86_64/egg/adb/filesync_protocol.py", line 213, in _ReadBuffered
  File "build/bdist.linux-x86_64/egg/adb/adb_protocol.py", line 113, in ReadUntil
  File "build/bdist.linux-x86_64/egg/adb/adb_protocol.py", line 239, in Read
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 4: ordinal not in range(128)
```

**Comment by phhusson** [comment]
@kronenpj As far as I can tell, the problem is that python2 support is broken, you need to use python3.
(Though python3 cli parsing is broken...)

**Comment by fahhem** [comment]
Python2 support should not be broken. I've just pushed a commit to fix the `map(ord())` issue in `CalculateChecksum()`. Is there another bug causing Python 2.7 to not work for you?

**Comment by phhusson** [comment]
Python 2.7.13
libusb1==1.5.3
m2crypto>=0.26.0
rsa>=3.4.2
Commit 8600f28e306919c35a6c492129a69efbda095a2b
```
$ PYTHONPATH=. python adb/adb_debug.py list /
Traceback (most recent call last):
  File "adb/adb_debug.py", line 178, in <module>
    sys.exit(main())
  File "adb/adb_debug.py", line 174, in main
    rsa_keys=[rsa_signer(path) for path in args.rsa_key_path])
  File "/home/phh/tmp/python-adb/adb/common_cli.py", line 150, in StartCli
    default_timeout_ms=args.timeout_ms, **device_kwargs)
  File "/home/phh/tmp/python-adb/adb/adb_commands.py", line 76, in ConnectDevice
    return cls.Connect(handle, **kwargs)
  File "/home/phh/tmp/python-adb/adb/adb_commands.py", line 99, in Connect
    device_state = cls.protocol_handler.Connect(usb, banner=banner, **kwargs)
  File "/home/phh/tmp/python-adb/adb/adb_protocol.py", line 287, in Connect
    cmd, arg0, arg1, banner = cls.Read(usb, ['CNXN', 'AUTH'])
  File "/home/phh/tmp/python-adb/adb/adb_protocol.py", line 239, in Read
    data += temp.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 0: ordinal not in range(128)
```

Python 2.7.13
libusb1==1.6.4
m2crypto>=0.26.0
rsa>=3.4.2
Commit 996b237c7e5cd431e7eee6752e59c70c0fcdfb80
```
Traceback (most recent call last):
  File "adb/adb_debug.py", line 178, in <module>
    sys.exit(main())
  File "adb/adb_debug.py", line 174, in main
    rsa_keys=[rsa_signer(path) for path in args.rsa_key_path])
  File "/home/phh/tmp/python-adb/adb/common_cli.py", line 150, in StartCli
    default_timeout_ms=args.timeout_ms, **device_kwargs)
  File "/home/phh/tmp/python-adb/adb/adb_commands.py", line 76, in ConnectDevice
    return cls.Connect(handle, **kwargs)
  File "/home/phh/tmp/python-adb/adb/adb_commands.py", line 99, in Connect
    device_state = cls.protocol_handler.Connect(usb, banner=banner, **kwargs)
  File "/home/phh/tmp/python-adb/adb/adb_protocol.py", line 301, in Connect
    msg.Send(usb)
  File "/home/phh/tmp/python-adb/adb/adb_protocol.py", line 211, in Send
    usb.BulkWrite(self.Pack(), timeout_ms)
  File "/home/phh/tmp/python-adb/adb/adb_protocol.py", line 198, in Pack
    len(self.data), self.checksum, self.magic)
  File "/home/phh/tmp/python-adb/adb/adb_protocol.py", line 182, in checksum
    return self.CalculateChecksum(self.data)
  File "/home/phh/tmp/python-adb/adb/adb_protocol.py", line 190, in CalculateChecksum
    total = sum(map(ord, data.decode('ascii')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 2: ordinal not in range(128)
```
