### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa1 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by xiaoxuetu** [google/python-adb#47]
branch：master(bed1a53d9574b6afbd63d783ed142371b0d1e584)
libusb1:1.6.4
os:centos

When I run the command `adb devices`, it is no problem:
```python
$ adb devices
List of devices attached
00d7d4dc428cab55        device
```

But When I run command `sudo python adb.zip devices`,it throw the error:
``` shell
# python adb.zip devices
00d7d4dc428cab55        device
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "adb.zip/__main__.py", line 178, in <module>
  File "adb.zip/__main__.py", line 161, in main
  File "adb.zip/__main__.py", line 52, in Devices
  File "adb.zip/adb/common.py", line 133, in serial_number
  File "/usr/lib/python2.7/site-packages/usb1/__init__.py", line 2040, in getSerialNumber
    self.device_descriptor.iSerialNumber)
  File "/usr/lib/python2.7/site-packages/usb1/__init__.py", line 2017, in _getASCIIStringDescriptor
    return self.open().getASCIIStringDescriptor(descriptor)
  File "/usr/lib/python2.7/site-packages/usb1/__init__.py", line 2067, in open
    mayRaiseUSBError(libusb1.libusb_open(self.device_p, byref(handle)))
  File "/usr/lib/python2.7/site-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/usr/lib/python2.7/site-packages/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorNoDevice: LIBUSB_ERROR_NO_DEVICE [-4]

```

**Comment by fahhem** [comment]
You need to run 'adb kill-server' otherwise we cannot talk to the device

**Comment by xiaoxuetu** [comment]
in my process, adb server was not running
![image](https://user-images.githubusercontent.com/6974781/27174030-375825c8-51ed-11e7-8323-d48e0ae94b54.png)

**Comment by fahhem** [comment]
Can you run 'adb kill-server' then python adb.zip devices? That is always the problem in my experience

**Comment by xiaoxuetu** [comment]
@fahhem It is not work and

``` shell

[root@82424eaf9717 python-adb-master]# adb kill-server
* server not running *
[root@82424eaf9717 python-adb-master]# python adb.zip devices
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "adb.zip/__main__.py", line 178, in <module>
  File "adb.zip/__main__.py", line 161, in main
  File "adb.zip/__main__.py", line 52, in Devices
  File "adb.zip/adb/common.py", line 133, in serial_number
  File "/usr/lib/python2.7/site-packages/usb1/__init__.py", line 2040, in getSerialNumber
    self.device_descriptor.iSerialNumber)
  File "/usr/lib/python2.7/site-packages/usb1/__init__.py", line 2017, in _getASCIIStringDescriptor
    return self.open().getASCIIStringDescriptor(descriptor)
  File "/usr/lib/python2.7/site-packages/usb1/__init__.py", line 2067, in open
    mayRaiseUSBError(libusb1.libusb_open(self.device_p, byref(handle)))
  File "/usr/lib/python2.7/site-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/usr/lib/python2.7/site-packages/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorNoDevice: LIBUSB_ERROR_NO_DEVICE [-4]

```

**Comment by fahhem** [comment]
Do you have other USB devices that may interfere? Can you unplug everything but the android device and narrow down what's causing it? This is the first time it opens the device, so it's not something the code can affect really

**Comment by xiaoxuetu** [comment]
I just found the reason。

I run python-adb in the docker container(centos7,libusb1:1.6.4)
```  shell
docker run -it --rm --device=/dev/bus/usb/003/062 uac/dockermanager /bin/bash
```

It will throw this error metioned above.

If I add the options `--privileged` ,it will be normal，But it will add all devices to the container.

I just want to add one device to the container and use python adb.

Do you know how to fix this problem?

**Comment by xiaoxuetu** [comment]
There is another question, Do you know how to use python-adb without root?

**Comment by fahhem** [comment]
I'm not familiar with USB devices in docker containers. python-adb doesn't need root if android's adb doesn't need it. If you have a common Android device, udev rules normally assign it to a group that your user has access to. If you don't, or you don't have the udev rules in the docker container, then you're going to need one of the following:
* Root, or
* Add a group your user is a part of to the device (either manually through sudo or automatically through udev), or
* Add your user to the group that the usb device is being assigned to

The way to find the usb device's user/group is to look at /dev/bus/usb/<bus>/<device>. You get <bus> and <device> by looking at `dmesg | tail` when plugging the device in. It'll say something like: `usb 1-3: new full-speed USB device number 20 using ...` so take the 1 from `1-3` and the 20 and you get /dev/bus/usb/001/020:

`ls -l /dev/bus/usb/001/020`

That should show you `root plugdev` or `root root`. If it says plugdev, ensure your user is in plugdev (most Linux flavors do that by default) with `groups | grep plugdev`. If it says root, then you need udev rules or you can manually do `sudo chgrp plugdev /dev/bus/usb/001/020` and you'll have access (until you unplug it or it reboots, then you'll have to do that again, with 021 since device numbers increment).

**Comment by xiaoxuetu** [comment]
After `ls -l /dev/bus/usb/001/020`, it show `root root` .

So I use root account to run the command.

## Question 1: Does python-adb support the specified device to execute shell commands?
Command: `python adb.zip -s 56a5ee9e --rsa_key_path /home/kevin/.android/adbkey shell ls`
ERROR:
``` shell
usage: adb.zip [-h] [--verbose] [--rsa_key_path ~/.android/adbkey]
               [--auth_timeout_s 60]
               {help,devices,install,list,logcat,push,pull,reboot,reboot-bootloader,remount,root,shell}
               ...
adb.zip: error: argument command_name: invalid choice: '56a5ee9e' (choose from 'help', 'devices', 'install', 'list', 'logcat', 'push', 'pull', 'reboot', 'reboot-bootloader', 'remount', 'root', 'shell')
`

## Question 2: UnicodeDecodeError: 'ascii' codec can't decode byte 0xa3 in position 2: ordinal not in range(128)
No matter I exec `python adb.zip shell ls` or `python adb.zip list .` , it always throw UnicodeDecodeError
```
$ python adb.zip shell ls
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "adb.zip/__main__.py", line 178, in <module>
  File "adb.zip/__main__.py", line 174, in main
  File "adb.zip/adb/common_cli.py", line 150, in StartCli
  File "adb.zip/adb/adb_commands.py", line 76, in ConnectDevice
  File "adb.zip/adb/adb_commands.py", line 99, in Connect
  File "adb.zip/adb/adb_protocol.py", line 298, in Connect
  File "adb.zip/adb/adb_protocol.py", line 211, in Send
  File "adb.zip/adb/adb_protocol.py", line 198, in Pack
  File "adb.zip/adb/adb_protocol.py", line 182, in checksum
  File "adb.zip/adb/adb_protocol.py", line 190, in CalculateChecksum
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa3 in position 2: ordinal not in range(128)
```

**Comment by michel-slm** [comment]
Getting that `UnicodeDecodeError` myself. @fahhem do you prefer this be turned into a new issue, since it's a different error from what was originally reported?

**Comment by fahhem** [comment]
Yes, it's a new issue and it's getting hard to keep track of it in this
thread. Is it the name as another issue? Also, is anyone willing to use a
branch I made to either test that it works or to gather information? I
suspect that my android devices don't use non-ascii in nearly enough places
to catch these issues myself without more unit test data.
