### ISSUE TITLE
Issue:  module' object has no attribute 'libusb_get_port_numbers'

### ISSUE THREAD

**Issue by tigerking** [google/python-adb#72]
when exec below command on MAC (high Sierra), it always report no attribute libusb_get_port_numbers issue. 

$ python adb.zip  list /sdcard/
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "adb.zip/__main__.py", line 178, in <module>
  File "adb.zip/__main__.py", line 174, in main
  File "adb.zip/adb/common_cli.py", line 150, in StartCli
  File "adb.zip/adb/adb_commands.py", line 75, in ConnectDevice
  File "adb.zip/adb/common.py", line 212, in FindAndOpen
  File "adb.zip/adb/common.py", line 93, in Open
  File "adb.zip/adb/common.py", line 138, in port_path
  File "/usr/local/lib/python2.7/site-packages/usb1.py", line 1510, in getPortNumberList
    result = libusb1.libusb_get_port_numbers(self.device_p, port_list,
AttributeError: 'module' object has no attribute 'libusb_get_port_numbers'

**Comment by fahhem** [comment]
That's a libusb version issue. The version of libusb1-dev installed in your system is too old, it needs to be 1.0.16+
