### ISSUE TITLE
adb_commands.AdbCommands.ConnectDevice(rsa_keys=[signer])

### ISSUE THREAD

**Issue by mutexliu** [google/python-adb#73]
the problem happened when running the example program in readme.

OS: MacOS 10.13
Phone: Huawei Mate 10.

the exception stack:
  File "PATH_TO_PROJECT/main.py", line 11, in <module>
    device = adb_commands.AdbCommands.ConnectDevice(banner='ok',rsa_keys=[signer])
  File "PATH_TO_PROJECT/env/lib/python2.7/site-packages/adb/adb_commands.py", line 76, in ConnectDevice
    return cls.Connect(handle, **kwargs)
  File "PATH_TO_PROJECT/env/lib/python2.7/site-packages/adb/adb_commands.py", line 99, in Connect
    device_state = cls.protocol_handler.Connect(usb, banner=banner, **kwargs)
  File "PATH_TO_PROJECT/env/lib/python2.7/site-packages/adb/adb_protocol.py", line 298, in Connect
    msg.Send(usb)
  File "PATH_TO_PROJECT/env/lib/python2.7/site-packages/adb/adb_protocol.py", line 211, in Send
    usb.BulkWrite(self.Pack(), timeout_ms)
  File "PATH_TO_PROJECT/env/lib/python2.7/site-packages/adb/adb_protocol.py", line 198, in Pack
    len(self.data), self.checksum, self.magic)
  File "PATH_TO_PROJECT/env/lib/python2.7/site-packages/adb/adb_protocol.py", line 182, in checksum
    return self.CalculateChecksum(self.data)
  File "PATH_TO_PROJECT/env/lib/python2.7/site-packages/adb/adb_protocol.py", line 190, in CalculateChecksum
    total = sum(map(ord, data.decode('ascii')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 0: ordinal not in range(128)

**Comment by qfmy92** [comment]
哥们，你是想做一个纯python版的跳一跳刷分外挂吧

**Comment by waza-ari** [comment]
I have exactly the same problem.

```
Traceback (most recent call last):
  File "/srv/firetv/bin/firetv-server", line 11, in <module>
    sys.exit(main())
  File "/srv/firetv/local/lib/python2.7/site-packages/firetv/__main__.py", line 237, in main
    if args.default and not add('default', args.default):
  File "/srv/firetv/local/lib/python2.7/site-packages/firetv/__main__.py", line 81, in add
    devices[device_id] = FireTV(str(host))
  File "/srv/firetv/local/lib/python2.7/site-packages/firetv/__init__.py", line 63, in __init__
    self.connect()
  File "/srv/firetv/local/lib/python2.7/site-packages/firetv/__init__.py", line 76, in connect
    serial=self.host, rsa_keys=[signer])
  File "/srv/firetv/local/lib/python2.7/site-packages/adb/adb_commands.py", line 76, in ConnectDevice
    return cls.Connect(handle, **kwargs)
  File "/srv/firetv/local/lib/python2.7/site-packages/adb/adb_commands.py", line 99, in Connect
    device_state = cls.protocol_handler.Connect(usb, banner=banner, **kwargs)
  File "/srv/firetv/local/lib/python2.7/site-packages/adb/adb_protocol.py", line 298, in Connect
    msg.Send(usb)
  File "/srv/firetv/local/lib/python2.7/site-packages/adb/adb_protocol.py", line 211, in Send
    usb.BulkWrite(self.Pack(), timeout_ms)
  File "/srv/firetv/local/lib/python2.7/site-packages/adb/adb_protocol.py", line 198, in Pack
    len(self.data), self.checksum, self.magic)
  File "/srv/firetv/local/lib/python2.7/site-packages/adb/adb_protocol.py", line 182, in checksum
    return self.CalculateChecksum(self.data)
  File "/srv/firetv/local/lib/python2.7/site-packages/adb/adb_protocol.py", line 190, in CalculateChecksum
    total = sum(map(ord, data.decode('ascii')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 0: ordinal not in range(128)
```

Any ideas? Thanks in advance

**Comment by waza-ari** [comment]
Never mind - looks like commit e8a6f84 (see #52) fixed it. Using master branch instead of latest release seams to work better.
