### ISSUE TITLE
TypeError while using Python3.6 with python-rsa

### ISSUE THREAD

**Issue by YSunLIN** [google/python-adb#86]
I tried to use python-adb with Python3.6 and python-rsa, then I got the TypeError while connecting to the device:
```python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "D:\DevTools\python-adb-master\adb\adb_commands.py", line 76, in ConnectDevice
    return cls.Connect(handle, **kwargs)
  File "D:\DevTools\python-adb-master\adb\adb_commands.py", line 99, in Connect
    device_state = cls.protocol_handler.Connect(usb, banner=banner, **kwargs)
  File "D:\DevTools\python-adb-master\adb\adb_protocol.py", line 299, in Connect
    signed_token = rsa_key.Sign(str(banner))
  File "D:\DevTools\python-adb-master\adb\sign_pythonrsa.py", line 69, in Sign
    return rsa.sign(data, self.priv_key, 'SHA-1-PREHASHED')
  File "D:\ProgramFiles\Python\Python36\lib\site-packages\rsa\pkcs1.py", line 275, in sign
    cleartext = asn1code + hash
TypeError: can't concat str to bytes
```

**Comment by Myonium** [comment]
If you take the latest github release there are only 2 minimal changes necessary to get it running under python3.6:
```
diff --git a/adb/adb_commands.py b/adb/adb_commands.py
index eb454ce..e0fc71d 100644
--- a/adb/adb_commands.py
+++ b/adb/adb_commands.py
@@ -67,7 +67,7 @@ class AdbCommands(object):
     If serial specifies a TCP address:port, then a TCP connection is
     used instead of a USB connection.
     """
-    if serial and b':' in serial:
+    if serial and ':' in serial:
         handle = common.TcpHandle(serial, timeout_ms=default_timeout_ms)
     else:
         handle = common.UsbHandle.FindAndOpen(
diff --git a/adb/common.py b/adb/common.py
index 9e1fc17..e43c9ec 100644
--- a/adb/common.py
+++ b/adb/common.py
@@ -291,8 +291,8 @@ class TcpHandle(object):
 
     Host may be an IP address or a host name.
     """
-    if b':' in serial:
-      (host, port) = serial.split(b':')
+    if ':' in serial:
+      (host, port) = serial.split(':')
     else:
       host = serial
       port = 5555
```

**Comment by fahhem** [comment]
@Myonium, if you make that a pull request I'll accept it asap :)

Also, include a change to `CONTRIBUTORS`

**Comment by YSunLIN** [comment]
@Myonium It can resolve the TypeError thrown in `TcpHandle`, but it cannot resolve the TypeError thrown in `python-rsa`.
