### ISSUE TITLE
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]

### ISSUE THREAD

**Issue by llliuyx** [google/python-adb#93]
Hello，the problem happened when I run the demo code.
OS：macOS Sierra 10.12
Android Phone: Huawei Mate8, Android 7.0
python dependencies:
adb (1.2.0)
libusb1 (1.6.4)
M2Crypto (0.29.0)
rsa (3.4.2)

The code about
device = adb_commands.AdbCommands.ConnectDevice(rsa_keys=[signer])
raise  __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)

Traceback (most recent call last):
  File "/.../PycharmProjects/AndroidPerformanceTest/adb_exp.py", line 13, in <module>
    rsa_keys=[signer])
  File "/.../PycharmProjects/AndroidPerformanceTest/virtual_env/AndroidPerformanceTest/lib/python2.7/site-packages/adb/adb_commands.py", line 75, in ConnectDevice
    timeout_ms=default_timeout_ms)
  File "/.../PycharmProjects/AndroidPerformanceTest/virtual_env/AndroidPerformanceTest/lib/python2.7/site-packages/adb/common.py", line 211, in FindAndOpen
    dev.Open()
  File "/.../PycharmProjects/AndroidPerformanceTest/virtual_env/AndroidPerformanceTest/lib/python2.7/site-packages/adb/common.py", line 122, in Open
    handle.claimInterface(iface_number)
  File "/.../PycharmProjects/AndroidPerformanceTest/virtual_env/AndroidPerformanceTest/lib/python2.7/site-packages/usb1/__init__.py", line 1276, in claimInterface
    libusb1.libusb_claim_interface(self.__handle, interface),
  File "/.../PycharmProjects/AndroidPerformanceTest/virtual_env/AndroidPerformanceTest/lib/python2.7/site-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/.../PycharmProjects/AndroidPerformanceTest/virtual_env/AndroidPerformanceTest/lib/python2.7/site-packages/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]

**Comment by fahhem** [comment]
This error always happens when the adb server is running, `adb kill-server` will get rid of it (unless it comes back right away because another program is running adb commands). If the server is gone, then you should be able to run the above normally. If you're going to update to master, update your code:

```py
device = adb_commands.AdbCommands()
device.ConnectDevice(rsa_keys=[signer])
```

**Comment by llliuyx** [comment]
I got it, Thank you very much.
