### ISSUE TITLE
Attached device not found

### ISSUE THREAD

**Issue by noxdafox** [google/python-adb#98]
Device running on Android Emulator on Debian 9 with Python 3.

```bash 
$ adb devices -l
List of devices attached
emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:11

$ python3 adb.zip devices

```

Same with the Python library:
```python
In [1]: from adb import adb_commands

In [2]: list(adb_commands.AdbCommands.Devices())
Out[2]: []

In [3]: adb_commands.AdbCommands.ConnectDevice(serial='emulator-5554')
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/adb/common.py in FindFirst(cls, setting_matcher, device_matcher, **kwargs)
    255             return next(cls.FindDevices(
--> 256                 setting_matcher, device_matcher=device_matcher, **kwargs))
    257         except StopIteration:

StopIteration: 

During handling of the above exception, another exception occurred:

DeviceNotFoundError                       Traceback (most recent call last)
<ipython-input-3-ef65bdc4c112> in <module>()
----> 1 adb_commands.AdbCommands.ConnectDevice(serial='emulator-5554')

/usr/local/lib/python3.5/dist-packages/adb/adb_commands.py in ConnectDevice(cls, port_path, serial, default_timeout_ms, **kwargs)
     75             handle = common.UsbHandle.FindAndOpen(
     76                 DeviceIsAvailable, port_path=port_path, serial=serial,
---> 77                 timeout_ms=default_timeout_ms)
     78         return cls.Connect(handle, **kwargs)
     79 

/usr/local/lib/python3.5/dist-packages/adb/common.py in FindAndOpen(cls, setting_matcher, port_path, serial, timeout_ms)
    215         dev = cls.Find(
    216             setting_matcher, port_path=port_path, serial=serial,
--> 217             timeout_ms=timeout_ms)
    218         dev.Open()
    219         dev.FlushBuffers()

/usr/local/lib/python3.5/dist-packages/adb/common.py in Find(cls, setting_matcher, port_path, serial, timeout_ms)
    235             usb_info = 'first'
    236         return cls.FindFirst(setting_matcher, device_matcher,
--> 237                              usb_info=usb_info, timeout_ms=timeout_ms)
    238 
    239     @classmethod

/usr/local/lib/python3.5/dist-packages/adb/common.py in FindFirst(cls, setting_matcher, device_matcher, **kwargs)
    257         except StopIteration:
    258             raise usb_exceptions.DeviceNotFoundError(
--> 259                 'No device available, or it is in the wrong configuration.')
    260 
    261     @classmethod

DeviceNotFoundError: No device available, or it is in the wrong configuration.
```

**Comment by fahhem** [comment]
Did you use the pypi release or tip-of-tree master? I need to make a new PyPI release soon, as the old one is very old and buggy (especially with Python3)

**Comment by noxdafox** [comment]
I tried both actually. The one mentioned above is the one from PyPi with a few fixes of mine (issues #34 and #69).

When trying the one from the master branch I kept getting errors like the one below which suggested me the API had changed.
```
In [1]: from adb import adb_commands

In [2]: list(adb_commands.AdbCommands.Devices())
Out[2]: []

In [3]: adb_commands.AdbCommands.ConnectDevice(serial='emulator-5554')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-ef65bdc4c112> in <module>()
----> 1 adb_commands.AdbCommands.ConnectDevice(serial='emulator-5554')

TypeError: ConnectDevice() missing 1 required positional argument: 'self'
```

**Comment by fahhem** [comment]
Ah, yes, the docs haven't been updated yet! For connecting, use an instance of `AdbCommands`: 

```py
adb = adb_commands.AdbCommands()
adb.ConnectDevice(...)
```

Python-adb doesn't find non-USB devices at the moment, `FindDevices` is specifically using USB APIs. I haven't looked into how emulators show up, maybe it's over TCP? If you find out how the emulator is found, then I'd be happy to add that to `FindDevices`, especially since we support TCP and could probably support whatever the emulator uses.

**Comment by fahhem** [comment]
Hmm, the second one is the right way, and it's connecting over TCP correctly, but the emulator is responding oddly... You need to make sure the normal adb server isn't around to mess with us: `adb kill-server`

**Comment by noxdafox** [comment]
Uhm... I am issuing `adb kill-server` but it seems something is bringing it back up. Could It be the android emulator itself?

**Comment by fahhem** [comment]
I don't know, do you have an IDE or something issuing adb commands? Any adb command will bring the server back

**Comment by noxdafox** [comment]
Not really, I am starting the emulator from the command line:

```bash
$ ./emulator -avd test -use-system-libs
```
```bash
$ ps aux | grep adb
noxdafox 20611  0.1  0.0 331400  4252 ?        Ssl  22:31   0:00 adb -L tcp:5037 fork-server server --reply-fd 6
```

Nothing else should be.

**Comment by noxdafox** [comment]
It seems the `adb` daemon is required by the emulator itself. I also tried to kill it and quickly connect with `python-adb` and I got the same error. I am pretty sure the `adb` daemon was not interfering at that point.

Did anyone try `python-adb` with the official android emulator?

**Comment by fahhem** [comment]
Then we don't support emulator access! I can't fight with the adb server, it will send commands randomly and throw off the protocol. The protocol is point-to-point, so the adbd running on the device/emulator doesn't track 'clients' so the state will drift each time a command is sent

**Comment by fahhem** [comment]
Sorry, since this wasn't developed in the Android side of Google, we don't get any special consideration. Maybe one day they'll have a flag in the emulator to disable the official adb server being brought up

**Comment by kolayne** [comment]
Hello, @fahhem! Tell me, if I should start a new issue to discuss this

I'm having the problem similar to described in this issue, but I think, it has a different reason. I'm using the official emulator from cmd-line (aka don't have an IDE calling `adb` etc), but as expected, `adb` is not automatically started. But I am still getting the error.

I am using `python-adb` from the top commit of master from [this repository](https://github.com/4oo4/python-adb) because it contains a fix of another issue I'm having, but it looks like the changes in that branch are not related to the error. My Python version is `3.8.2`. No idea how to find out my emulator's version

Code/output:
```bash
nikolay@KoLin:~$ adb devices  # Adb sees the emulator device
List of devices attached
* daemon not running; starting now at tcp:5037
* daemon started successfully
emulator-5554	device

nikolay@KoLin:~$ adb shell  # Adb does successfully connect to the emulator device
generic_x86_arm:/ $ exit
nikolay@KoLin:~$ adb kill-server  # Let's kill it!
nikolay@KoLin:~$ cat tmp.py  # Here is my code sample
import os.path as op

from adb import sign_cryptography, adb_commands


signer = sign_cryptography.CryptographySigner(op.expanduser('~/.android/adbkey'))
device = adb_commands.AdbCommands()
print(list(device.Devices()))
print()
device.ConnectDevice(rsa_keys=[signer])
nikolay@KoLin:~$ python3 tmp.py  # Running it results into an error :(
[]

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/adb/common.py", line 256, in FindFirst
    return next(cls.FindDevices(
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tmp.py", line 10, in <module>
    device.ConnectDevice(rsa_keys=[signer])
  File "/usr/local/lib/python3.8/dist-packages/adb/adb_commands.py", line 138, in ConnectDevice
    self._handle = common.UsbHandle.FindAndOpen(
  File "/usr/local/lib/python3.8/dist-packages/adb/common.py", line 218, in FindAndOpen
    dev = cls.Find(
  File "/usr/local/lib/python3.8/dist-packages/adb/common.py", line 237, in Find
    return cls.FindFirst(setting_matcher, device_matcher,
  File "/usr/local/lib/python3.8/dist-packages/adb/common.py", line 259, in FindFirst
    raise usb_exceptions.DeviceNotFoundError(
adb.usb_exceptions.DeviceNotFoundError: No device available, or it is in the wrong configuration.
nikolay@KoLin:~$ ps aux | grep adb  # But adb server was not restarted, it's not the reason of the above error
nikolay   209792  0.0  0.0   9036   732 pts/0    S+   22:59   0:00 grep --color=auto adb
nikolay@KoLin:~$
```

Is there a way to connect to an emulator with your library in this situation?
