### ISSUE TITLE
USB1 USBErrorNotSupported: LIBUSB_ERROR_NOT_SUPPORTED [-12]

### ISSUE THREAD

**Issue by baruchl** [google/python-adb#99]
Running the following code on Win10, using [pypi 1.2 package ](https://pypi.python.org/pypi/adb/1.2.0) (I had to install manually LibUsb1 and copied the LibUSB1-0.dll to local directory):
```
    import os.path as op
    from adb import adb_commands
    from adb import sign_m2crypto

    #KitKat+ devices require authentication
    signer = sign_m2crypto.M2CryptoSigner(op.expanduser("~/.android/adbkey"))
    # Connect to the device
    device = adb_commands.AdbCommands(None, None)
    # device.ConnectDevice()
    device.ConnectDevice(rsa_keys=[signer])
```

Gives me the following error:
Traceback (most recent call last):
  File "<input>", line 10, in <module>
  File "C:\Users\baruchl\PycharmProjects\TM2_VAL_LAB\venv\lib\site-packages\adb\adb_commands.py", line 75, in ConnectDevice
    timeout_ms=default_timeout_ms)
  File "C:\Users\baruchl\PycharmProjects\TM2_VAL_LAB\venv\lib\site-packages\adb\common.py", line 211, in FindAndOpen
    dev.Open()
  File "C:\Users\baruchl\PycharmProjects\TM2_VAL_LAB\venv\lib\site-packages\adb\common.py", line 112, in Open
    handle = self._device.open()
  File "C:\Users\baruchl\PycharmProjects\TM2_VAL_LAB\venv\lib\site-packages\usb1\__init__.py", line 2067, in open
    mayRaiseUSBError(libusb1.libusb_open(self.device_p, byref(handle)))
  File "C:\Users\baruchl\PycharmProjects\TM2_VAL_LAB\venv\lib\site-packages\usb1\__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "C:\Users\baruchl\PycharmProjects\TM2_VAL_LAB\venv\lib\site-packages\usb1\__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]

Another strange issue is that if I run adb_commands.AdbCommands(None, None) with no arguments as described in the readme file, I get a the following error:
'__init__() takes exactly 3 arguments (1 given)'

**Comment by fahhem** [comment]
Please ensure adb's normal server isn't running: `adb kill-server` then check that it's not running in the background anymore using the task manager.

**Comment by baruchl** [comment]
Thanks @fahhem , I have ensured that no ADB server is running.
When it is running, it's just like issue https://github.com/google/python-adb/issues/93, and the error received is LIBUSB_ERROR_ACCESS [-3], so this must be something different.

**Comment by fahhem** [comment]
This is the same error that happens when the server is running. If you can access the device using adb shell, then when the server is killed, you should be able to use then it should work.

For the PyPI release, you should be using the older code:

```py
device = AdbCommands.ConnectDevice(...)
```

**Comment by baruchl** [comment]
@fahhem  - i have just noticed I copied the wrong traceback in the original comment. I fixed it. Please take a look - it is LIBUSB_ERROR_NOT_SUPPORTED [-12], and no ADB running in the background (I double check it)

**Comment by baruchl** [comment]
I changed the method as you recommended (AdbCommands.ConnectDevice) with the same results (LIBUSB_ERROR_NOT_SUPPORTED [-12],)

**Comment by baruchl** [comment]
Thanks @fahhem  much appreciated!
Please note I opened a new issue :(
#103
